name: nekoze_notify
description: "猫背通知"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_airpods: ^1.0.5
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1
  flutter_riverpod: ^2.6.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true